name: CI-CD

permissions:
  contents: write  # Autorise l'écriture (push) dans le repo depuis GitHub Actions

on:
  pull_request:
    branches: [ "dev" ]
  push:
    branches: [ "dev", "staging", "main" ]

jobs:
  build-and-test:
    # Se lance sur toutes les branches indiquées dans on.push et on.pull_request
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest
          pip install -r app/requirements.txt

      - name: Run tests (integration)
        run: |
          pytest tests/integration

  push-to-staging:
    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0   # important pour voir toutes les branches si besoin
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Push dev to staging
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          # On pousse directement la branche dev vers la branche staging
          git push origin dev:staging --force

  staging-build-test-main:
    if: github.ref == 'refs/heads/staging' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest
          pip install -r app/requirements.txt

      - name: Run all tests
        run: |
          pytest tests

      - name: Push staging to main
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          # On pousse directement staging vers main
          git push origin staging:main

  production-deploy:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Docker login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t iznomoule/ml-in-prod-final:latest .
          docker tag iznomoule/ml-in-prod-final:latest iznomoule/ml-in-prod-final:${{ github.run_number }}

      - name: Push Docker image
        run: |
          docker push iznomoule/ml-in-prod-final:latest
          docker push iznomoule/ml-in-prod-final:${{ github.run_number }}

      - name: Deploy to Cloud
        run: |
          echo "Deploying to Cloud..."
          # Commandes spécifiques à la plateforme de déploiement
