name: CI-CD

on:
  pull_request:
    branches: [ "dev" ]
  push:
    branches: [ "dev", "staging", "main" ]

jobs:
  build-and-test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest
          pip install -r app/requirements.txt

      - name: Run tests (integration)
        run: |
          pytest tests/integration

  push-to-staging:
    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2   # ← IMPORTANT : clonage pour pouvoir utiliser git

      - name: Push to staging
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          # Si la branche staging existe déjà, tu peux remplacer par 'git checkout staging'
          git checkout -b staging
          git push origin staging

  staging-build-test-main:
    if: github.ref == 'refs/heads/staging' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest
          pip install -r app/requirements.txt

      - name: Run all tests
        run: |
          pytest tests

      - name: Push to main
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          # Idem, si la branche main existe déjà, remplace par un checkout normal
          git checkout -b main
          git push origin main

  production-deploy:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Docker login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t iznomoule/ml-in-prod-final:latest .
          docker tag iznomoule/ml-in-prod-final:latest iznomoule/ml-in-prod-final:${{ github.run_number }}

      - name: Push Docker image
        run: |
          docker push iznomoule/ml-in-prod-final:latest
          docker push iznomoule/ml-in-prod-final:${{ github.run_number }}

      - name: Deploy to Cloud
        run: |
          # Exemple : déploiement sur Koyeb/Railway
          echo "Deploying to Cloud..."
          # Commandes spécifiques à la plateforme choisie
